import { expect, test } from '@playwright/test';

test('Card Storage sizing, dividers, exports and persistence', async ({ page }) => {
  test.setTimeout(120_000);
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: '+ Add loose tray', exact: true }).first().click();
  await page.getByRole('button', { name: 'Card Storage One cavity with removable, labelled dividers' }).click();
  const editor = page.locator('.storageEditor');
  await expect(editor.getByLabel('Number of cards')).toHaveValue('100');
  await editor.getByLabel('Label', { exact: true }).fill('Acción');
  await editor.getByLabel('Label', { exact: true }).press('Tab');
  const originalDimensions = await editor.locator('.summary').innerText();
  await editor.getByRole('button', { name: 'Add divider', exact: true }).click();
  await expect(editor.locator('fieldset')).toHaveCount(2);
  const defaultDividerColour = await editor.getByLabel('Default divider colour').inputValue();
  expect(defaultDividerColour).toMatch(/^#[0-9a-f]{6}$/i);
  await expect(editor.locator('fieldset').nth(1).getByLabel('Colour')).toHaveValue(defaultDividerColour);
  await editor.locator('fieldset').first().getByLabel('Colour').fill('#ff0000');
  await editor.locator('fieldset').nth(1).getByLabel('Colour').fill('#0000ff');
  await expect(editor.locator('.summary')).not.toHaveText(originalDimensions);
  await editor.getByLabel('Size by').selectOption('length');
  await editor.getByLabel('Exterior length (mm)').fill('150');
  await editor.getByLabel('Maximum total height (mm)').fill('60');
  await editor.getByRole('combobox', { name: 'Closure', exact: true }).selectOption('sliding');
  await editor.getByLabel('Lid text', { exact: true }).fill('Cards');
  await editor.getByLabel('Lid text', { exact: true }).press('Tab');
  await editor.getByRole('combobox', { name: 'Lid text mode', exact: true }).selectOption('inlay');
  await expect(editor.locator('.error')).toHaveCount(0);
  await expect(editor.locator('.summary')).toContainText('150.0 × 60.0 mm');
  // The application debounces project saves; wait for the last edit before reloading.
  await expect.poll(() => page.evaluate(() => Object.values(localStorage).some(value => value.includes('"lidTextMode":"inlay"')))).toBe(true);
  await page.reload();
  await page.getByRole('button', { name: /Card Storage .* loose$/ }).click();
  await expect(editor.getByLabel('Exterior length (mm)')).toHaveValue('150');
  await expect(editor.getByRole('combobox', { name: 'Closure', exact: true })).toHaveValue('sliding');
  await expect(editor.getByLabel('Lid text', { exact: true })).toHaveValue('Cards');
  await expect(editor.getByRole('combobox', { name: 'Lid text mode', exact: true })).toHaveValue('inlay');
  await editor.getByLabel('Show lid closed in preview').check();
  await expect.poll(() => page.evaluate(() => Object.values(localStorage).some(value => value.includes('"previewLid":true')))).toBe(true);
  await expect(page.locator('.generatingOverlay')).toHaveCount(0, {timeout:30000});
  await page.screenshot({path:test.info().outputPath('card-storage-closed.png')});
  await editor.getByRole('combobox', { name: 'Closure', exact: true }).selectOption('none');
  await expect(editor.getByLabel('Lid text', { exact: true })).toHaveCount(0);
  await editor.getByRole('combobox', { name: 'Closure', exact: true }).selectOption('sliding');
  await expect(editor.getByLabel('Lid text', { exact: true })).toHaveValue('Cards');
  await expect(editor.locator('fieldset')).toHaveCount(2);
  await expect(editor.getByLabel('Label', { exact: true }).first()).toHaveValue('Acción');
  await expect(editor.locator('fieldset').first().getByLabel('Colour')).toHaveValue('#ff0000');
  await expect(editor.locator('fieldset').nth(1).getByLabel('Colour')).toHaveValue('#0000ff');
  await editor.getByRole('combobox', { name: 'Parts', exact: true }).selectOption({ label: 'Divider 1: Acción' });
  const download = page.waitForEvent('download');
  await editor.getByRole('button', { name: 'Export 3MF', exact: true }).click();
  expect((await download).suggestedFilename()).toMatch(/\.3mf$/);
  await editor.getByRole('combobox', { name: 'Parts', exact: true }).selectOption('lid');
  const lidDownload = page.waitForEvent('download');
  await editor.getByRole('button', { name: 'Export 3MF', exact: true }).click();
  expect((await lidDownload).suggestedFilename()).toMatch(/lid\.3mf$/);
  await editor.getByRole('combobox', { name: 'Parts', exact: true }).selectOption('all');
  const zip = page.waitForEvent('download');
  await editor.getByRole('button', { name: 'Export STL', exact: true }).click();
  expect((await zip).suggestedFilename()).toMatch(/parts.zip$/);
  await editor.getByLabel('Maximum total height (mm)').fill('10');
  await editor.getByLabel('Maximum total height (mm)').press('Tab');
  await expect(editor.getByRole('button', { name: 'Export 3MF', exact: true })).toBeDisabled();
  await expect(editor.getByRole('alert').first()).toContainText('Maximum height');
  expect(errors).toEqual([]);
});
